Sort block
gvwilson/tidyblocks pull request #153
Opened 2019-09-06 18:03 UTC by MayaGans

- create sort block with descending checkbox
- delete old sort block
- delete descending block
- update documentation to reflect new block
- delete reverse block documentation

2019-09-06 18:09 UTC, gvwilson approved these changes
Two minor questions - looks good.

2019-09-06 18:09 UTC, gvwilson commented on _posts/2019-08-26-values.md
> +    <h3>Description: The If - Then - Else block first checks its boolean condition. If the condition is true, the code held inside the Then space will activate, and the script will continue. If the c
Should probably say that this is done row-by-row - maybe a small HTML table showing an example?

2019-09-06 18:09 UTC, gvwilson commented on _posts/2019-08-29-transform.md
> +    <p><b>Checkbox: </b>Check to sort table in descending order</p>
Hm - just realized that there's no way to sort ascending by one column and descending by another, but how often does that ever come up?

2019-09-07 01:18 UTC, gvwilson requested changes
Please use `npm run test` to run the tests and update those as well to match these changes.

2019-09-12 16:25 UTC, MayaGans commented
VERY proud of this one !

- changed `sort` method to include `reverse` parameter (boolean for box checked)
- test_codegen for single column, multiple columns, multiple columns descending
- didn't touch test_exec (still works!)
- changed descending check box to `DESCENDING` to keep consistent

2019-09-12 16:36 UTC, gvwilson requested changes
Good work - small changes request.

2019-09-12 16:36 UTC, gvwilson commented on _posts/2019-08-26-values.md
> +    <h3>Description: The If - Then - Else block first checks its boolean condition.
Doesn't belong in this pull request (has nothing to do with sorting).

2019-09-12 16:36 UTC, gvwilson commented on _posts/2019-08-29-transform.md
> +    <p>Order table rows by an expression involving its variables. Use the checkbox for descending the order of rows.</p>
"Use the checkbox to sort in descending order."

2019-09-12 16:36 UTC, gvwilson commented on _posts/2019-08-29-transform.md
> +    <p><b>Text Field: </b>The name of the column(s) to arrange the rows by -- seperated by commas.</p>
1. Use "," instead of "--".
2. "separated" not "seperated"

2019-09-12 16:36 UTC, gvwilson commented on generators/js/transform_sort.js
>          .split(',')
we should probably write a helper function for this some day...

2019-09-12 16:36 UTC, gvwilson commented on generators/js/transform_sort.js
> +if (block.getFieldValue('DESCENDING') == 'FALSE') {
or:

```
const descending = (block.getFieldValue('DESCENDING') === 'FALSE')
return `.sort(${block.tbId}, [${columns}], ${descending})`
```

2019-09-12 16:36 UTC, gvwilson commented on test/test_js_exec.js
> +        DESCENDING: 'FALSE'})
indent by one

2019-09-12 16:36 UTC, gvwilson commented on test/test_js_error.js
> +        {MULTIPLE_COLUMNS: ''},
this still looks wrong (two objects instead of one)

2019-09-12 16:36 UTC, gvwilson commented on test/test_js_codegen.js
> +    DESCENDING: 'TRUE'})
indent by one so that the keys line up

2019-09-12 16:36 UTC, gvwilson commented on test/test_js_codegen.js
> +      DESCENDING: 'FALSE'})
indent by one so that the keys line up

2019-09-12 16:36 UTC, gvwilson commented on tidyblocks/tidyblocks.js
> +    if (reverse === false) {
this can more simply be written:

```
if (reverse) {
  result.reverse()
}
return new TidyBlocksDataFrame(result)
```

Remember, a Boolean can be used directly in a test because it *is* either `true` or `false` - any time you're comparing something with `(value === true)` or `(value === false)`, you can and should simplify.

2019-09-12 19:34 UTC, merged